// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSQpOb0i7YTbCDF9dY7DE5BslvSIqTwFg',
    appId: '1:247110518106:web:28df5c8f07a304adf55f63',
    messagingSenderId: '247110518106',
    projectId: 'insightt-e77ee',
    authDomain: 'insightt-e77ee.firebaseapp.com',
    databaseURL: 'https://insightt-e77ee-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'insightt-e77ee.appspot.com',
    measurementId: 'G-PYKV4P4JF2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVj4Ihw_lytSONtqQEpThiDbxYvc2ZwxE',
    appId: '1:247110518106:android:ee7d013f770e3347f55f63',
    messagingSenderId: '247110518106',
    projectId: 'insightt-e77ee',
    databaseURL: 'https://insightt-e77ee-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'insightt-e77ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5XOoKl_oqCikdysRTYjatoSbG7V1Nzwg',
    appId: '1:247110518106:ios:737e351d5029cc9cf55f63',
    messagingSenderId: '247110518106',
    projectId: 'insightt-e77ee',
    databaseURL: 'https://insightt-e77ee-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'insightt-e77ee.appspot.com',
    iosBundleId: 'com.example.insight',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5XOoKl_oqCikdysRTYjatoSbG7V1Nzwg',
    appId: '1:247110518106:ios:737e351d5029cc9cf55f63',
    messagingSenderId: '247110518106',
    projectId: 'insightt-e77ee',
    databaseURL: 'https://insightt-e77ee-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'insightt-e77ee.appspot.com',
    iosBundleId: 'com.example.insight',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSQpOb0i7YTbCDF9dY7DE5BslvSIqTwFg',
    appId: '1:247110518106:web:acbfcdf451f2819ef55f63',
    messagingSenderId: '247110518106',
    projectId: 'insightt-e77ee',
    authDomain: 'insightt-e77ee.firebaseapp.com',
    databaseURL: 'https://insightt-e77ee-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'insightt-e77ee.appspot.com',
    measurementId: 'G-CCN6SEGB59',
  );
}
